# Generated by Django 2.2.1 on 2019-06-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prices',
            new_name='price',
        ),
    ]
